### ISSUE TITLE
Not Building

### ISSUE THREAD

**Issue by git-anurag** [DrGodCarl/hashids-objc#2]
It’s not building getting the error as “architecture x84_64 not found”
I am using hashids for my iPhone app.
![screen shot 2017-09-19 at 1 09 58 pm](https://user-images.githubusercontent.com/14774875/30581081-85384df0-9d3c-11e7-86fc-d1f8836f35da.png)

**Comment by DrGodCarl** [comment]
While I'm running into the same issues while working on turning this into a Cocoa Pod I suspect that this is because you failed to recursively clone the project.
